-- Stores user-provided campus point coordinates.
CREATE TABLE IF NOT EXISTS public.campus_waypoints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  x REAL NOT NULL,
  y REAL NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO public.campus_waypoints (name, x, y) VALUES
('Auditorium 1', 950, 260),
('Auditorium 2', 950, 655),
('Seminar Hall', 950, 455),
('Lab 1', 690, 605),
('Lab 2', 865, 605),
('Lab 3', 865, 515),
('Lab 4', 865, 325),
('Lab 5', 810, 310),
('PT room', 725, 310),
('Store Room', 675, 310),
('Transport Office', 625, 310),
('AIDS Department', 690, 555),
('2nd AIDS ''A''', 690, 475),
('1st AIDS ''B''', 690, 395),
('Green Room', 690, 345),
('Boys RestRoom', 595, 605),
('Girls RestRoom', 395, 605),
('VIP Pantry', 355, 605),
('VIP Waiting Area', 310, 605),
('Pantry', 175, 605),
('VIP Dining', 135, 605),
('Chairman Office', 115, 605),
('Principle Office', 95, 605),
('OAT', 810, 455),
('Admin Office', 310, 365),
('Reception', 135, 455),
('Master Board Room', 135, 515),
('OAK leaf', 135, 555),
('Exam Cell', 310, 495),
('Meeting Room', 310, 555),
('Zig Zag Steps', 495, 310),
('Admission Office', 395, 310),
('Falcon Hall', 310, 310),
('Harmony', 145, 310),
('CDC', 185, 310),
('Symphony', 95, 310),
('Waiting Hall', 135, 355),
('OSSIS Hall', 205, 605),
('D Block', 865, 455),
('D Block 2', 865, 605),
('D Block 3', 865, 310),
('C Block', 690, 455),
('C Block 2', 690, 605),
('C Block 3', 690, 310),
('Middle Block', 515, 455),
('Middle Block 2', 515, 605),
('Middle Block 3', 515, 310),
('B Block', 310, 455),
('B Block 2', 310, 605),
('B Block 3', 310, 310),
('A Block', 135, 455),
('A Block 2', 135, 605),
('A Block 3', 135, 310)
ON CONFLICT (name) DO UPDATE
SET x = EXCLUDED.x,
    y = EXCLUDED.y;

-- Import room points into the app's waypoints table.
-- All are seeded on ground floor as requested; corridors/edges can be added later.
INSERT INTO public.waypoints (name, floor, x, y, type, block)
SELECT
  cw.name,
  'G'::public.floor_type,
  cw.x,
  cw.y,
  'room'::public.waypoint_type,
  CASE
    WHEN cw.x <= 250 THEN 'A'
    WHEN cw.x <= 430 THEN 'B'
    WHEN cw.x <= 620 THEN 'M'
    WHEN cw.x <= 790 THEN 'C'
    ELSE 'D'
  END AS block
FROM public.campus_waypoints AS cw
ON CONFLICT (name, floor) DO UPDATE
SET x = EXCLUDED.x,
    y = EXCLUDED.y,
    type = EXCLUDED.type,
    block = EXCLUDED.block;
