-- Stores user-provided campus point coordinates.
CREATE TABLE IF NOT EXISTS public.campus_waypoints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  x REAL NOT NULL,
  y REAL NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO public.campus_waypoints (name, x, y) VALUES
('Auditorium 1', 950, 260),
('Auditorium 2', 950, 655),
('Seminar Hall', 950, 455),
('Lab 1', 690, 605),
('Lab 2', 865, 605),
('Lab 3', 865, 515),
('Lab 4', 865, 325),
('Lab 5', 810, 310),
('PT room', 725, 310),
('Store Room', 675, 310),
('Transport Office', 625, 310),
('AIDS Department', 690, 555),
('2nd AIDS ''A''', 690, 475),
('1st AIDS ''B''', 690, 395),
('Green Room', 690, 345),
('Boys RestRoom', 595, 605),
('Girls RestRoom', 395, 605),
('VIP Pantry', 355, 605),
('VIP Waiting Area', 310, 605),
('Pantry', 175, 605),
('VIP Dining', 135, 605),
('Chairman Office', 115, 605),
('Principle Office', 95, 605),
('OAT', 810, 455),
('Admin Office', 310, 365),
('Reception', 135, 455),
('Master Board Room', 135, 515),
('OAK leaf', 135, 555),
('Exam Cell', 310, 495),
('Meeting Room', 310, 555),
('Zig Zag Steps', 495, 310),
('Admission Office', 395, 310),
('Falcon Hall', 310, 310),
('Harmony', 145, 310),
('CDC', 185, 310),
('Symphony', 95, 310),
('Waiting Hall', 135, 355),
('OSSIS Hall', 205, 605),
('D Block', 865, 455),
('D Block 2', 865, 605),
('D Block 3', 865, 310),
('C Block', 690, 455),
('C Block 2', 690, 605),
('C Block 3', 690, 310),
('Middle Block', 515, 455),
('Middle Block 2', 515, 605),
('Middle Block 3', 515, 310),
('B Block', 310, 455),
('B Block 2', 310, 605),
('B Block 3', 310, 310),
('A Block', 135, 455),
('A Block 2', 135, 605),
('A Block 3', 135, 310)
ON CONFLICT (name) DO UPDATE
SET x = EXCLUDED.x,
    y = EXCLUDED.y;

-- Import room points into the app's waypoints table.
-- All are seeded on ground floor as requested; corridors/edges can be added later.
INSERT INTO public.waypoints (name, floor, x, y, type, block)
SELECT
  cw.name,
  'G'::public.floor_type,
  cw.x,
  cw.y,
  'room'::public.waypoint_type,
  CASE
    WHEN cw.x <= 250 THEN 'A'
    WHEN cw.x <= 430 THEN 'B'
    WHEN cw.x <= 620 THEN 'M'
    WHEN cw.x <= 790 THEN 'C'
    ELSE 'D'
  END AS block
FROM public.campus_waypoints AS cw
ON CONFLICT (name, floor) DO UPDATE
SET x = EXCLUDED.x,
    y = EXCLUDED.y,
    type = EXCLUDED.type,
    block = EXCLUDED.block;

-- Seed graph edges from the provided adjacency map.
WITH graph_json AS (
  SELECT $$
  {
    "Auditorium 2": { "Seminar Hall": 20, "Auditorium 1": 25 },
    "Auditorium 1": { "Seminar Hall": 10, "Auditorium 2": 25 },
    "Seminar Hall": { "Auditorium 1": 10, "Auditorium 2": 20, "D Block": 10 },
    "Lab 1": { "D Block 2": 10, "C Block": 20, "Boys RestRoom": 10 },
    "Lab 2": { "D Block 2": 10 },
    "Lab 3": { "D Block": 20, "D Block 2": 10 },
    "Lab 4": { "D Block": 10, "D Block 3": 10 },
    "Lab 5": { "D Block 3": 10, "PT room": 10 },
    "D Block": { "Lab 3": 10, "Lab 4": 15, "Seminar Hall": 10 },
    "D Block 2": { "Lab 2": 10, "Lab 1": 10, "Lab 3": 20 },
    "D Block 3": { "Lab 4": 10, "Lab 5": 10 },
    "PT room": { "Lab 5": 10, "C Block 3": 10 },
    "C Block": { "2nd AIDS 'A'": 10, "1st AIDS 'B'": 10, "OAT": 10 },
    "C Block 2": { "AIDS Department": 10, "Lab 1": 10 },
    "C Block 3": { "Green Room": 10, "PT room": 10, "Store Room": 10 },
    "Store Room": { "C Block 3": 10, "Transport Office": 10 },
    "Transport Office": { "Store Room": 10, "Middle Block 3": 10 },
    "AIDS Department": { "2nd AIDS 'A'": 10, "C Block 2": 10 },
    "2nd AIDS 'A'": { "AIDS Department": 10, "C Block": 10 },
    "1st AIDS 'B'": { "Green Room": 10, "C Block": 10 },
    "Green Room": { "1st AIDS 'B'": 10, "C Block 3": 10 },
    "Boys RestRoom": { "Lab 1": 10, "Middle Block 2": 10 },
    "Girls RestRoom": { "Middle Block 2": 10, "VIP Pantry": 10 },
    "Middle Block": { "Middle Block 2": 10, "Middle Block 3": 10 },
    "Middle Block 2": { "Middle Block": 10, "Girls RestRoom": 10, "Boys RestRoom": 10 },
    "VIP Pantry": { "Girls RestRoom": 10, "VIP Waiting Area": 10 },
    "VIP Waiting Area": { "VIP Pantry": 10, "B Block 2": 10, "OSSIS Hall": 10 },
    "Meeting Room": { "B Block 2": 10, "Exam Cell": 10 },
    "Exam Cell": { "Meeting Room": 10, "B Block": 10 },
    "B Block": { "Exam Cell": 10, "Admin Office": 10, "A Block": 10 },
    "B Block 2": { "VIP Waiting Area": 10, "Meeting Room": 10 },
    "Admin Office": { "B Block": 10, "Falcon Hall": 10 },
    "B Block 3": { "Admission Office": 10, "Falcon Hall": 10, "CDC": 10 },
    "Falcon Hall": { "B Block 3": 10, "Admin Office": 10 },
    "CDC": { "B Block 3": 10, "Harmony": 10 },
    "Harmony": { "CDC": 10, "A Block 3": 10 },
    "A Block": { "B Block": 10, "Reception": 10, "Master Board Room": 10 },
    "A Block 2": { "OAK leaf": 10, "VIP Dining": 10 },
    "A Block 3": { "Symphony": 10, "Harmony": 10, "Waiting Hall": 10 },
    "Symphony": { "A Block 3": 10 },
    "Waiting Hall": { "A Block 3": 10, "Reception": 10 },
    "Reception": { "A Block": 10, "Waiting Hall": 10 },
    "Master Board Room": { "A Block": 10, "OAK leaf": 10 },
    "OAK leaf": { "Master Board Room": 10, "A Block 2": 10 },
    "VIP Dining": { "A Block 2": 10, "Chairman Office": 10, "Pantry": 10 },
    "Chairman Office": { "VIP Dining": 10, "Principle Office": 10 },
    "Principle Office": { "Chairman Office": 10 },
    "OAT": { "C Block": 10 },
    "Pantry": { "VIP Dining": 10, "OSSIS Hall": 10 },
    "OSSIS Hall": { "Pantry": 10, "VIP Waiting Area": 10 },
    "Zig Zag Steps": { "Admission Office": 10, "Middle Block 3": 10 },
    "Middle Block 3": { "Zig Zag Steps": 10, "Middle Block": 10, "Transport Office": 10 },
    "Admission Office": { "Zig Zag Steps": 10, "B Block 3": 10 }
  }
  $$::jsonb AS g
),
raw_edges AS (
  SELECT
    from_node.key AS from_node,
    to_node.key AS to_node,
    (to_node.value)::REAL AS distance
  FROM graph_json gj
  CROSS JOIN LATERAL jsonb_each(gj.g) AS from_node(key, value)
  CROSS JOIN LATERAL jsonb_each(from_node.value) AS to_node(key, value)
),
dedup_edges AS (
  SELECT
    LEAST(from_node, to_node) AS from_node,
    GREATEST(from_node, to_node) AS to_node,
    MIN(distance) AS distance
  FROM raw_edges
  GROUP BY 1, 2
)
INSERT INTO public.graph_edges (from_node, to_node, distance, floor, is_vertical)
SELECT
  de.from_node,
  de.to_node,
  de.distance,
  'G'::public.floor_type,
  FALSE
FROM dedup_edges de
ON CONFLICT (from_node, to_node) DO UPDATE
SET
  distance = EXCLUDED.distance,
  floor = EXCLUDED.floor,
  is_vertical = EXCLUDED.is_vertical;
